### PR TITLE
Add Open Liberty as option for UI dev (with dev mode hot reload)

### PR DESCRIPTION
**Pull request by scottkurz**
Not trying to push Open Liberty on anybody, but I found it convenient to be able to use the hot reload in Liberty "dev mode", so am sharing that as an option for anyone else who find this useful.

It should have zero impact on anyone not using Liberty.

### CODE REVIEW

**Comment by m-reza-rahman** [comment]
How important is this at the moment? Our currently chosen cloud hosting option is App Service JBoss EAP, so Liberty would only be valid for local development.

**Comment by scottkurz** [comment]
Sorry, was only doing it thinking it wouldn't get in the way of the path for the hosted env.  But let's not worry about it for now.

**Comment by m-reza-rahman** [comment]
OK. We could certainly revisit this in the future. We are technically not bound by a hosting choice.

**Comment by scottkurz** [comment]
For anyone still reading, no changes are really needed.  (I didn't realize this was using EE 8 JSF).  You can just run with:
> mvn io.openliberty.tools:liberty-maven-plugin:3.7.1:dev -DgenerateFeatures --file ui/pom.xml

**Pull request closed without merging**
