### PR TITLE
#248 Improve look and feel of UI

### PR DESCRIPTION
**Pull request by kito99**
Addresses #248.

### CODE REVIEW

**Comment by kito99** [comment]
I'm getting this error for the ECA: 

image

Not quite sure what the deal is...kito-public@virtua.tech is a valid email, but it's not the one I'm using for either my Github or Eclipse accounts.

**Comment by jeyvison** [comment]
Hi, @kito99 :) Can you please amend your commits with the email you used to sign the ECA, please?

**Comment by m-reza-rahman** [comment]
Hi @ivargrimstad, could you possibly help debug? I honestly have no idea.

**Comment by scottkurz** [comment]
Is there an easy way to shrink the size of the banner at the top?  It still looks just as big to me in building and running locally.

I don't mean to criticize this PR if this was not something you were trying to accomplish here.  However, that to me seemed to be the biggest "look and feel" issue, and so, if there's something easy we could do to shrink this further, maybe we could still try that?  Sorry, not too familiar with the UI elements myself.

**Comment by m-reza-rahman** [comment]
Hi @ivargrimstad, could you please comment on the above? I agree with Scott. That said, I understand we need to conform to the look and feel of the jakarta.ee site.

**Comment by kito99** [comment]
@scottkurz the banner will be addressed in #246. It's out of scope for this issue (#248).

**Comment by kito99** [comment]
Replaced by #252.

**Pull request closed without merging**
