### PR TITLE
Indent velocity macros

### PR DESCRIPTION
**Pull request by OndroMih**
With a maven plugin that removes the indentation in the artifact because velocity would leave it in the final files.

This makes it easier to read and write the source code and the indented space has no impact on generated files.

This change doesn't change any behavior of the final archetype artifact, only indentation in the source files.

Passes the nightly build executed against my branch: https://github.com/OndroMih/jakartaee-starter/actions/runs/10427857106

### CODE REVIEW

**Comment by m-reza-rahman** [comment]
Please look into build failures.

**Comment by m-reza-rahman** [comment]
Did you check to see if the nightly build also works? Since this could break things, I’ll need to look carefully before I merge. I am off this week, so may be a little while. I do want to get the Docker support in sooner rather than later, so it’s a priority.

**Comment by OndroMih** [comment]
I've fixed the build failures. They happened because the Github action uses an old maven and thus old antrun plugin, which for reasons unknown to me didn't execute the target at all. The latest antrun plugin fixed that and the velocity files are properly un-indented.

I also started a nightly build in my branch, it's still running, without any failure so far: https://github.com/OndroMih/jakartaee-starter/actions/runs/10427857106

**Comment by m-reza-rahman** [comment]
Trying to understand - so the Archetype will now require a newer version of Maven? How new? Is this really worth it or will this cause users grief? Remember, we do still support quite old stuff in general in the Starter.

**Comment by OndroMih** [comment]
No, no need for newer maven. All works normally, without any change to the CI configuration.. Sorry for confusion. I just needed to define explicit version of antrun plugin to use, not rely on the default provided by maven, which was too old. When I set explicit antrun version to `3.1.0` all works now. 

This pull request has no impact on users, the generated archetype will be the same as before. It only allows us to have indentation in the files with velocity markup, while the resulting files in the archetype are the same as before. The antrun plugin removes the indentation. In short, the source code is different, more readable, but the final archetype is the same as before.

**Comment by m-reza-rahman** [comment]
OK. I’ll take a look ASAP.

**Review by m-reza-rahman — CHANGES_REQUESTED** [review]
I was able to look at the changes very closely and also test things out to a reasonable extent. The good news is that no bugs were introduced that I am able to see. However, there are a few issues I would like you to kindly address. Once those are addressed, please take the PR out of draft mode and I will review carefully once again.

* Can you please apply Velocity indentation uniformly across all files? Otherwise this can cause confusion. For example, the Velocity content in the web.xml file and the Liberty configuration is not indented.
* One weakness here is that if someone uses Velocity directives we do not currently use, things might break. Looking at the current Velocity syntax: https://velocity.apache.org/engine/devel/user-guide.html, I think the biggest possible problem is with contributors introducing single line Velocity comments. Can you please update the RegEx to handle that case (and also kindly test it)? Other than that, can you please note this possible problem in the Contributor Guide (in addition to noting which files are being pre-processed): https://github.com/eclipse-ee4j/starter/blob/master/CONTRIBUTING.md. If we run across this, we will need to further update the RegEx/AntRun invocation. If we don't clearly document this now, it may cause confusion down the road.

**Comment by m-reza-rahman** [comment]
Being moved forward here: https://github.com/eclipse-ee4j/starter/pull/340. I hope that is OK. I know we are all busy.

**Comment by OndroMih** [comment]
Sure, thank you.

**Pull request closed without merging**
