### PR TITLE
Update nightly.yml

### PR DESCRIPTION
**Pull request by ojuschugh1**
Test the running generated project via Maven (e.g. call the REST endpoint) Test the running generated project via Docker

### CODE REVIEW

**Comment by m-reza-rahman** [comment]
Is this a draft PR that you are still working on? If so, please mark it as such. Otherwise, please open PRs that are complete, self-sufficient and add a specific value to the project. The PR in it's current form does not do that.

**Comment by ojuschugh1** [comment]
i have added code to test -:
Test the running generated project via Maven (e.g. call the REST endpoint) 
Test the running generated project via Docker
as addressed here More robust nightly build #185.

**Comment by m-reza-rahman** [comment]
This is basically redundant code that does not actually do much.

**Comment by ojuschugh1** [comment]
ok got it sir,Sorry for disturbing your time :(

**Pull request closed without merging**
