### PR TITLE
Prepare for Jakarta EE 11 release (separate branch)

### PR DESCRIPTION
**Pull request by geziefer**
Re-submitted to keep on separate branch jakartaee11:

This change was discussed at OCX Germany together with Reza and Ivar.
The plan is to have an archetype ready when EE 11 is finally released (currently M4).
For that everything is prepared in that PR in order to have 11 ready for selection and in validations and tests.
There are still TODOs in it and for the final release the version has to be adapted.
So far, only GlassFish (currently M8 of v8) is supported for the start.

### CODE REVIEW

**Comment by m-reza-rahman** [comment]
Hi @geziefer, do you know why the ECA is failing? If it's easily fixable, let's kindly go ahead and do it. I don't want this to become some kind of IP issue later on.

**Comment by geziefer** [comment]
@m-reza-rahman It is failing, because in my profile there is only my company e-mail alexander.ruehl@sti.valantic.com, but I also work on my private laptop which uses alexander@dieruehls.de, where the latter has no signed ECA since Eclipse profile does not allow to add another e-mail address.

**Comment by geziefer** [comment]
I was told by Maria to create a second account with my other e-mail, which I just did. Now the check is fine.

**Comment by m-reza-rahman** [comment]
OK. I'll now move this forward. Thanks for getting this rolling.

**Pull request merged**
