### PR TITLE
Add Jakarta EE Starter Code UI Features

### PR DESCRIPTION
**Pull request by rokon12**
This is a simple UI and it does not yet connect to the backend with all the features that are available in the UI. I have not been able to make much progress on it recently, but if anyone is interested in contributing, please feel free to take the initiative. I will be away for a bit, but I hope to return soon.

### CODE REVIEW

**Comment by m-reza-rahman** [comment]
I'll get this ready to merge.

**Comment by m-reza-rahman** [comment]
Please begin reviewing this, @nikitakoselev.

**Comment by nikitakoselev** [comment]
I am looking into the ticket, thank you ☺

**Comment by nikitakoselev** [comment]
My first question is - how to test the UI?
The target/jakarta-starter-ui.war file doesn't get generated by running "mvn clean package", 
so there is nothing to deploy to Tomcat. 

Docker image generation command "docker build -t eclise/starter-ui ." also required the war file.

**Comment by m-reza-rahman** [comment]
Hello @nikitakoselev, you should treat the current state as work in progress. I doubt if anything is in functional state just yet.

**Comment by nikitakoselev** [comment]
What is our policy towards small bugs?
Shall I raise separate tickets for small things, forr example, artifact/jakarta-starter-ui.war file, which was configured in Docker file as target/jakarta-starter-ui.war
Or it is preferred to solve them as part of bigger tickets, so we do not drown in hundreds of small tickets?

**Comment by m-reza-rahman** [comment]
It's up to you really. Personally I would focus on getting the work outlined here done rather than spending time/effort opening/closing a bunch of small issues. That's what I would have done.

**Comment by m-reza-rahman** [comment]
Closing this to create a fresh one.

**Pull request closed without merging**
