### PR TITLE
Check Dockerfile build for None and WIldFly runtimes

### PR DESCRIPTION
**Pull request by Tasnim1147**

### CODE REVIEW

**Comment by Tasnim1147** [comment]
I have added a shell script check to verify whether a Dockerfile is generated after the archetype run. I am concerned that this might make the code heavy when accounting for all possible combinations. Please let me know if any improvements are needed.

**Review by m-reza-rahman — CHANGES_REQUESTED** [review]
No need to check if a Docker file was unnecessarily generated. This excessive. Is that what you were intending to do or do you need to re-work this?

**Comment by Tasnim1147** [comment]
Yes, I was trying to test that the Dockerfile is generated where it is supposed to be and ensure that it isn't generated where it shouldn't be.

**Comment by m-reza-rahman** [comment]
OK. Let's not worry about the latter case. For the former, let's attempt an actual Docker build as a more robust test.

**Comment by m-reza-rahman** [comment]
The approach you took is good for the negative cases where a Dockerfile was not generated because the user input incorrectly asked for one.

**Comment by Tasnim1147** [comment]
Removed the unnecessary checks and add `docker build` for generated Dockerfiles.

**Review by m-reza-rahman — CHANGES_REQUESTED** [review]
No need to check for file existence. The build will fail anyway if there isn’t a Dockerfile.

**Pull request merged**
