### PR TITLE
Add embedded maven wrapper

### PR DESCRIPTION
**Pull request by rokon12**

### CODE REVIEW

**Comment by m-reza-rahman** [comment]
This looks good. I will test it out as soon as I am able. We should update the documentation accordingly.

**Comment by jeyvison** [comment]
Just tested it on Mac. Looks great. @m-reza-rahman if tou could confim it works ona windoes machine i think we can merge it. If yo're not able i can teste it in a vm tomorrow

**Comment by jeyvison** [comment]
Thinking about the docs now, isince this change does not have doc updates i think we should open an issue so we can deal with it

**Comment by m-reza-rahman** [comment]
You can close this, @rokon12. I have already tested, documented and incorporated the Maven Wrapper into both Archetypes via #105.

**Comment by rokon12** [comment]
Closing it, as @m-reza-rahman  incorporated in his PR.

**Pull request closed without merging**
