### PR TITLE
Implementing #274: Add input fields for maven coordinates for project creation

### PR DESCRIPTION
**Pull request by geziefer**
Feature implemented as described in #274 

Tests done:
- empty input fields
- invalid input fields
- input with and without leaving input field
- generation with defaults
- generation with new values
  - check for java packages
  - check for maven file

### CODE REVIEW

**Comment by geziefer** [comment]
For some reason, a wrong email address slipped in - the one labled as not being covered by leagal agreement (alexander.ruehl.sti@valantic.com) is wrong, correct is alexander.ruehl@sti.valantic.com) - what do I have to do to fix that?

**Comment by jeyvison** [comment]
hi @geziefer , you can try to rebase you commits ammending the author in each one of them.

**Comment by geziefer** [comment]
@jeyvison Do I have to do it for continuing with the PR? I wonder, why this was not a problem in previous commits, since this seemed to be wrong in my git config from the beginning of my participation.

**Comment by jeyvison** [comment]
@geziefer You do, since we cant get contribuitions without a valid ECA. Have you checked if ([alexander.ruehl.sti@valantic.com](mailto:alexander.ruehl.sti@valantic.com)) had an ECA attached to it and for some reason it expired? Maybe thats the case.

**Comment by geziefer** [comment]
@jeyvison Ok, I'll try the rebase/ammend and file new PR. No it did not expire, it was just a typo in my git config email I didn't notice yet.

**Pull request closed without merging**
