### PR TITLE
GlassFish and TomEE support

### PR DESCRIPTION
**Pull request by m-reza-rahman**
Feel free to merge when ready. This is ready to go into a subsequent release.

### CODE REVIEW

**Comment by m-reza-rahman** [comment]
@ivargrimstad, can you please check what the ECA issue is about? I have an updated ECA. Is this just triggered by the number of changes?

**Comment by TanjaObradovic** [comment]
@m-reza-rahman this seems to be all around problem. Our team is trying to resolve as quickly as possible. Please try again in a few hours or tomorrow. Thanks!

**Comment by m-reza-rahman** [comment]
Will do @TanjaObradovic. If it's just a commit size issue, I can easily break it up into two commits. To be honest though, this all would be a lot easier and faster if I just was a committer.

**Comment by m-reza-rahman** [comment]
Hmm. Are the requirements the same as specification projects or is it more like Cargo Tracker? In other words, is an ECA enough for this project as committer? If not, I really can't be a committer as a Microsoft employee. In fact, even contributing is a very gray area in terms of IP. Could you please help clarify, @TanjaObradovic? To be very honest, I think it is highly unlikely at this juncture that Microsoft will join the Jakarta EE working group. This is a reason I don't contribute to many other things like the Tutorial and Examples.

**Comment by m-reza-rahman** [comment]
I thought I already did all of that for Cargo Tracker and the ECA, but I will check again. Just giving me consent to work on it in my own time is not a problem. I can get any paperwork needed signed.

**Comment by m-reza-rahman** [comment]
The ECA issue is resolved now. This can be merged. In the meantime, I will also make sure I have all the paperwork for committer rights.

**Pull request merged**
